'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class C_old_V_CLSG_RAPP_TCBL
    Public Property ID_PSG As Long
    Public Property DT_SCAN As Date
    Public Property DT_EXPE As Nullable(Of Date)
    Public Property NU_CART As String
    Public Property NU_CMD As String
    Public Property NU_BL As String
    Public Property CD_CRTN As String
    Public Property NU_SER_ECO As String
    Public Property NU_SER_CLIE As String
    Public Property NU_OF As Nullable(Of Integer)
    Public Property QT_CRTN As String
    Public Property NU_PALE As String
    Public Property ID_VERS_SOFT As String

End Class
