'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class DTM_REF_ID_TEST
    Public Property ID_TEST As Integer
    Public Property NM_DSGT_TEST As String
    Public Property ID_GAMM_PROD As Byte
    Public Property BL_ATVT As Nullable(Of Boolean)
    Public Property DT_CREA As Nullable(Of Date)

End Class
