'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class DTM_NMCT_PROD
    Public Property NU_SER_SPFE As String
    Public Property CD_ARTI_PROD As String
    Public Property NU_SER_COMP As String
    Public Property CD_ARTI_COMP As String
    Public Property BL_TYPE_TCBL As Nullable(Of Boolean)
    Public Property BL_APVS_ECO As Nullable(Of Boolean)
    Public Property NU_VERS_COMP As Nullable(Of Short)
    Public Property DT_AFCT As Nullable(Of Date)
    Public Property NM_DSGT_COMP As String

End Class
