'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class DTM_RESU_TEST_LIST
    Public Property NU_SER_SPFE As String
    Public Property NU_TEST As Byte
    Public Property CD_ARTI_PROD As String
    Public Property NM_RFRC_SEQU As String
    Public Property NU_VERS_SEQU As Nullable(Of Byte)
    Public Property ID_RFRC_SEQU As Long
    Public Property NM_RFRC_FDV As String
    Public Property NU_VERS_FDV As Nullable(Of Byte)
    Public Property ID_STAT_PROD As Nullable(Of Byte)
    Public Property BL_STAT_PROD As Nullable(Of Boolean)
    Public Property NU_OF As Nullable(Of Integer)
    Public Property DT_TEST As Nullable(Of Date)
    Public Property ID_OPRT As Nullable(Of Short)

End Class
