'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class DTM_HSQR_STAT_PROD
    Public Property NU_SER_SPFE As String
    Public Property NU_TEST As Byte
    Public Property ID_RFRC_SEQU As Long
    Public Property NU_PHAS As Short
    Public Property ID_STAT_PROD As Nullable(Of Byte)
    Public Property DT_STAT_PROD As Date
    Public Property ID_OPRT As Nullable(Of Short)
    Public Property ID_POST As String

End Class
