'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class DTM_SEQU_RFRC_LIST
    Public Property NM_RFRC_SEQU As String
    Public Property NU_VERS_SEQU As Byte
    Public Property ID_RFRC_SEQU As Long
    Public Property DT_APCT As Nullable(Of Date)
    Public Property DT_VLDT As Nullable(Of Date)
    Public Property BL_VLDT As Nullable(Of Boolean)
    Public Property NM_VALI_ALMS As String
    Public Property NM_VALI_ECO As String
    Public Property NM_RFRC_GAMM_ECO As String

End Class
