'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class DTM_LOG_APP_WEB
    Public Property NM_POST As String
    Public Property DT_LOG As Date
    Public Property NM_FONC As String
    Public Property NM_MSG As String
    Public Property NM_CTCT As String

End Class
