'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class DTM_ADRE_MAC
    Public Property NU_ADRE_MAC As String
    Public Property CD_ARTI_CART As String
    Public Property CD_ARTI_PROD As String
    Public Property NU_BANC As String
    Public Property BL_RSVT As Nullable(Of Boolean)

End Class
