'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class DTM_NC_LIST
    Public Property ID_TYPE_NC As Nullable(Of Byte)
    Public Property NU_INCI As Integer
    Public Property NU_SER_SPFE As String
    Public Property CD_ARTI_PROD As String
    Public Property NU_DRGT As String

End Class
