'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class DWH_DIM_DEVDEUI
    Public Property NU_OF As Integer
    Public Property CD_DEVDEUI As String
    Public Property CD_MDP As String
    Public Property NU_NS As String
    Public Property LB_STA As String

End Class
