'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class DWH_REF_ARTI_CLT
    Public Property CD_ARTI As String
    Public Property LB_CMRC As String
    Public Property LB_EOL As String
    Public Property CD_PN As String
    Public Property NU_VRSN As String

End Class
