'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class DWH_DIM_WRKF
    Public Property ID_PSG As Integer
    Public Property DT_PSG As Nullable(Of Date)
    Public Property NU_OF As Nullable(Of Integer)
    Public Property CD_ARTI As String
    Public Property NU_NS As String
    Public Property BL_STA As Nullable(Of Boolean)
    Public Property NU_ETP As Nullable(Of Short)

End Class
