'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ID_Conteneur_View
    Public Property ID_GST_CNTR As Integer
    Public Property NM_CNTR As String
    Public Property DT_PREP As Nullable(Of Date)
    Public Property LB_SERV_PREP As String
    Public Property ID_CPT As String
    Public Property NM_QTE_INIT As Nullable(Of Single)
    Public Property NM_QTE As Nullable(Of Single)
    Public Property DT_LCSN As Nullable(Of Date)
    Public Property LB_LCSN As String
    Public Property NM_OF As Nullable(Of Integer)
    Public Property NM_SAP_CPT As String

End Class
