'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure
Imports System.Data.Entity.Core.Objects
Imports System.Linq

Partial Public Class SENSINGLABS_PRDEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=SENSINGLABS_PRDEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property DWH_DIM_CPT_CRTQ() As DbSet(Of DWH_DIM_CPT_CRTQ)
    Public Overridable Property DWH_DIM_DEVDEUI() As DbSet(Of DWH_DIM_DEVDEUI)
    Public Overridable Property DWH_DIM_WRKF() As DbSet(Of DWH_DIM_WRKF)
    Public Overridable Property DWH_HIST_LIVR() As DbSet(Of DWH_HIST_LIVR)
    Public Overridable Property DWH_REF_ARTI_CLT() As DbSet(Of DWH_REF_ARTI_CLT)
    Public Overridable Property DWH_REF_ARTI_PARAM() As DbSet(Of DWH_REF_ARTI_PARAM)
    Public Overridable Property DWH_REF_ETP_PRCS() As DbSet(Of DWH_REF_ETP_PRCS)
    Public Overridable Property TMP_PST_CLSG() As DbSet(Of TMP_PST_CLSG)
    Public Overridable Property V_TCBL_TOUT() As DbSet(Of V_TCBL_TOUT)

    Public Overridable Function PRC_ATTR_DEVEUI(nU_NS As String, result As ObjectParameter, dEVEUI As ObjectParameter) As Integer
        Dim nU_NSParameter As ObjectParameter = If(nU_NS IsNot Nothing, New ObjectParameter("NU_NS", nU_NS), New ObjectParameter("NU_NS", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("PRC_ATTR_DEVEUI", nU_NSParameter, result, dEVEUI)
    End Function

    Public Overridable Function PRC_BSCL_CLSG_TMP_HIST(lB_PST As String, [eRROR] As ObjectParameter) As Integer
        Dim lB_PSTParameter As ObjectParameter = If(lB_PST IsNot Nothing, New ObjectParameter("LB_PST", lB_PST), New ObjectParameter("LB_PST", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("PRC_BSCL_CLSG_TMP_HIST", lB_PSTParameter, [eRROR])
    End Function

    Public Overridable Function PRC_DEL_TMP_PST_CLSG(lB_PST As String) As Integer
        Dim lB_PSTParameter As ObjectParameter = If(lB_PST IsNot Nothing, New ObjectParameter("LB_PST", lB_PST), New ObjectParameter("LB_PST", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("PRC_DEL_TMP_PST_CLSG", lB_PSTParameter)
    End Function

    Public Overridable Function PRC_DEL_TMP_PST_CLSG_NS(lB_PST As String, nU_NS As String) As Integer
        Dim lB_PSTParameter As ObjectParameter = If(lB_PST IsNot Nothing, New ObjectParameter("LB_PST", lB_PST), New ObjectParameter("LB_PST", GetType(String)))

        Dim nU_NSParameter As ObjectParameter = If(nU_NS IsNot Nothing, New ObjectParameter("NU_NS", nU_NS), New ObjectParameter("NU_NS", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("PRC_DEL_TMP_PST_CLSG_NS", lB_PSTParameter, nU_NSParameter)
    End Function

    Public Overridable Function PRC_DEVEUI_TO_NS(cD_DEVDEUI As String, nU_NS As ObjectParameter) As Integer
        Dim cD_DEVDEUIParameter As ObjectParameter = If(cD_DEVDEUI IsNot Nothing, New ObjectParameter("CD_DEVDEUI", cD_DEVDEUI), New ObjectParameter("CD_DEVDEUI", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("PRC_DEVEUI_TO_NS", cD_DEVDEUIParameter, nU_NS)
    End Function

    Public Overridable Function PRC_ETQ_DEVEUI(cD_ARTI As String) As ObjectResult(Of PRC_ETQ_DEVEUI_Result)
        Dim cD_ARTIParameter As ObjectParameter = If(cD_ARTI IsNot Nothing, New ObjectParameter("CD_ARTI", cD_ARTI), New ObjectParameter("CD_ARTI", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of PRC_ETQ_DEVEUI_Result)("PRC_ETQ_DEVEUI", cD_ARTIParameter)
    End Function

    Public Overridable Function PRC_EXP_DEVEUI(rESULTAT As ObjectParameter) As Integer
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("PRC_EXP_DEVEUI", rESULTAT)
    End Function

    Public Overridable Function PRC_EXP_WK(rESULTAT As ObjectParameter) As Integer
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("PRC_EXP_WK", rESULTAT)
    End Function

    Public Overridable Function PRC_GSTN_ERR([eRROR] As ObjectParameter) As Integer
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("PRC_GSTN_ERR", [eRROR])
    End Function

    Public Overridable Function PRC_HIST_LIVR_DBL(nU_NS As String, [eRROR] As ObjectParameter) As Integer
        Dim nU_NSParameter As ObjectParameter = If(nU_NS IsNot Nothing, New ObjectParameter("NU_NS", nU_NS), New ObjectParameter("NU_NS", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("PRC_HIST_LIVR_DBL", nU_NSParameter, [eRROR])
    End Function

    Public Overridable Function PRC_IMP_RPT_BNC(rESULTAT As ObjectParameter) As Integer
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("PRC_IMP_RPT_BNC", rESULTAT)
    End Function

    Public Overridable Function PRC_INS_DEVDEUI(cD_DEVDEUI As String, nU_OF As Nullable(Of Integer), cD_MDP As String, [eRROR] As ObjectParameter) As Integer
        Dim cD_DEVDEUIParameter As ObjectParameter = If(cD_DEVDEUI IsNot Nothing, New ObjectParameter("CD_DEVDEUI", cD_DEVDEUI), New ObjectParameter("CD_DEVDEUI", GetType(String)))

        Dim nU_OFParameter As ObjectParameter = If(nU_OF.HasValue, New ObjectParameter("NU_OF", nU_OF), New ObjectParameter("NU_OF", GetType(Integer)))

        Dim cD_MDPParameter As ObjectParameter = If(cD_MDP IsNot Nothing, New ObjectParameter("CD_MDP", cD_MDP), New ObjectParameter("CD_MDP", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("PRC_INS_DEVDEUI", cD_DEVDEUIParameter, nU_OFParameter, cD_MDPParameter, [eRROR])
    End Function

    Public Overridable Function PRC_INS_ETP_WF(nU_OF As Nullable(Of Integer), cD_ARTI As String, nU_NS As String, bL_STA As Nullable(Of Boolean), nU_ETP As Nullable(Of Short), [eRROR] As ObjectParameter) As Integer
        Dim nU_OFParameter As ObjectParameter = If(nU_OF.HasValue, New ObjectParameter("NU_OF", nU_OF), New ObjectParameter("NU_OF", GetType(Integer)))

        Dim cD_ARTIParameter As ObjectParameter = If(cD_ARTI IsNot Nothing, New ObjectParameter("CD_ARTI", cD_ARTI), New ObjectParameter("CD_ARTI", GetType(String)))

        Dim nU_NSParameter As ObjectParameter = If(nU_NS IsNot Nothing, New ObjectParameter("NU_NS", nU_NS), New ObjectParameter("NU_NS", GetType(String)))

        Dim bL_STAParameter As ObjectParameter = If(bL_STA.HasValue, New ObjectParameter("BL_STA", bL_STA), New ObjectParameter("BL_STA", GetType(Boolean)))

        Dim nU_ETPParameter As ObjectParameter = If(nU_ETP.HasValue, New ObjectParameter("NU_ETP", nU_ETP), New ObjectParameter("NU_ETP", GetType(Short)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("PRC_INS_ETP_WF", nU_OFParameter, cD_ARTIParameter, nU_NSParameter, bL_STAParameter, nU_ETPParameter, [eRROR])
    End Function

    Public Overridable Function PRC_INS_TMP_CLSG(lB_PST As String, nM_OF As Nullable(Of Integer), cD_ARTI As String, lB_ARTI As String, nM_NS_EOL As String, nM_MATR As Nullable(Of Short), [eRROR] As ObjectParameter) As Integer
        Dim lB_PSTParameter As ObjectParameter = If(lB_PST IsNot Nothing, New ObjectParameter("LB_PST", lB_PST), New ObjectParameter("LB_PST", GetType(String)))

        Dim nM_OFParameter As ObjectParameter = If(nM_OF.HasValue, New ObjectParameter("NM_OF", nM_OF), New ObjectParameter("NM_OF", GetType(Integer)))

        Dim cD_ARTIParameter As ObjectParameter = If(cD_ARTI IsNot Nothing, New ObjectParameter("CD_ARTI", cD_ARTI), New ObjectParameter("CD_ARTI", GetType(String)))

        Dim lB_ARTIParameter As ObjectParameter = If(lB_ARTI IsNot Nothing, New ObjectParameter("LB_ARTI", lB_ARTI), New ObjectParameter("LB_ARTI", GetType(String)))

        Dim nM_NS_EOLParameter As ObjectParameter = If(nM_NS_EOL IsNot Nothing, New ObjectParameter("NM_NS_EOL", nM_NS_EOL), New ObjectParameter("NM_NS_EOL", GetType(String)))

        Dim nM_MATRParameter As ObjectParameter = If(nM_MATR.HasValue, New ObjectParameter("NM_MATR", nM_MATR), New ObjectParameter("NM_MATR", GetType(Short)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("PRC_INS_TMP_CLSG", lB_PSTParameter, nM_OFParameter, cD_ARTIParameter, lB_ARTIParameter, nM_NS_EOLParameter, nM_MATRParameter, [eRROR])
    End Function

    Public Overridable Function PRC_LST_ARTI() As ObjectResult(Of String)
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of String)("PRC_LST_ARTI")
    End Function

    Public Overridable Function PRC_LST_OF_NS_ETP(nU_OF As Nullable(Of Integer), nU_ETP As Nullable(Of Short)) As ObjectResult(Of String)
        Dim nU_OFParameter As ObjectParameter = If(nU_OF.HasValue, New ObjectParameter("NU_OF", nU_OF), New ObjectParameter("NU_OF", GetType(Integer)))

        Dim nU_ETPParameter As ObjectParameter = If(nU_ETP.HasValue, New ObjectParameter("NU_ETP", nU_ETP), New ObjectParameter("NU_ETP", GetType(Short)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of String)("PRC_LST_OF_NS_ETP", nU_OFParameter, nU_ETPParameter)
    End Function

    Public Overridable Function PRC_LST_TMP_CLSG_PST(lB_PST As String) As ObjectResult(Of PRC_LST_TMP_CLSG_PST_Result)
        Dim lB_PSTParameter As ObjectParameter = If(lB_PST IsNot Nothing, New ObjectParameter("LB_PST", lB_PST), New ObjectParameter("LB_PST", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of PRC_LST_TMP_CLSG_PST_Result)("PRC_LST_TMP_CLSG_PST", lB_PSTParameter)
    End Function

    Public Overridable Function PRC_MAJ_STT_DEVEUI(dEVEUI As String, nU_NS As String, lB_STA As String, result As ObjectParameter) As Integer
        Dim dEVEUIParameter As ObjectParameter = If(dEVEUI IsNot Nothing, New ObjectParameter("DEVEUI", dEVEUI), New ObjectParameter("DEVEUI", GetType(String)))

        Dim nU_NSParameter As ObjectParameter = If(nU_NS IsNot Nothing, New ObjectParameter("NU_NS", nU_NS), New ObjectParameter("NU_NS", GetType(String)))

        Dim lB_STAParameter As ObjectParameter = If(lB_STA IsNot Nothing, New ObjectParameter("LB_STA", lB_STA), New ObjectParameter("LB_STA", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("PRC_MAJ_STT_DEVEUI", dEVEUIParameter, nU_NSParameter, lB_STAParameter, result)
    End Function

    Public Overridable Function PRC_MDP_IMP(mDP As ObjectParameter) As Integer
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("PRC_MDP_IMP", mDP)
    End Function

    Public Overridable Function PRC_NS_TO_ARTI(nU_NS As String, cD_ARTI As ObjectParameter) As Integer
        Dim nU_NSParameter As ObjectParameter = If(nU_NS IsNot Nothing, New ObjectParameter("NU_NS", nU_NS), New ObjectParameter("NU_NS", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("PRC_NS_TO_ARTI", nU_NSParameter, cD_ARTI)
    End Function

    Public Overridable Function PRC_NS_TO_DEVEUI(nU_NS As String, cD_DEVDEUI As ObjectParameter) As Integer
        Dim nU_NSParameter As ObjectParameter = If(nU_NS IsNot Nothing, New ObjectParameter("NU_NS", nU_NS), New ObjectParameter("NU_NS", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("PRC_NS_TO_DEVEUI", nU_NSParameter, cD_DEVDEUI)
    End Function

    Public Overridable Function PRC_NS_TO_OF(nU_NS As String, nU_OF As ObjectParameter) As Integer
        Dim nU_NSParameter As ObjectParameter = If(nU_NS IsNot Nothing, New ObjectParameter("NU_NS", nU_NS), New ObjectParameter("NU_NS", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("PRC_NS_TO_OF", nU_NSParameter, nU_OF)
    End Function

    Public Overridable Function PRC_PARAM_ARTI(cD_ARTI As String) As ObjectResult(Of PRC_PARAM_ARTI_Result)
        Dim cD_ARTIParameter As ObjectParameter = If(cD_ARTI IsNot Nothing, New ObjectParameter("CD_ARTI", cD_ARTI), New ObjectParameter("CD_ARTI", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of PRC_PARAM_ARTI_Result)("PRC_PARAM_ARTI", cD_ARTIParameter)
    End Function

    Public Overridable Function PRC_PSG_DBL(nU_ETP As Nullable(Of Short), nU_NS As String, nB_PSG As ObjectParameter) As Integer
        Dim nU_ETPParameter As ObjectParameter = If(nU_ETP.HasValue, New ObjectParameter("NU_ETP", nU_ETP), New ObjectParameter("NU_ETP", GetType(Short)))

        Dim nU_NSParameter As ObjectParameter = If(nU_NS IsNot Nothing, New ObjectParameter("NU_NS", nU_NS), New ObjectParameter("NU_NS", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("PRC_PSG_DBL", nU_ETPParameter, nU_NSParameter, nB_PSG)
    End Function

    Public Overridable Function PRC_TMP_CLSG_DBL(lB_PST As String, nU_NS As String, nB_PSG As ObjectParameter) As Integer
        Dim lB_PSTParameter As ObjectParameter = If(lB_PST IsNot Nothing, New ObjectParameter("LB_PST", lB_PST), New ObjectParameter("LB_PST", GetType(String)))

        Dim nU_NSParameter As ObjectParameter = If(nU_NS IsNot Nothing, New ObjectParameter("NU_NS", nU_NS), New ObjectParameter("NU_NS", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("PRC_TMP_CLSG_DBL", lB_PSTParameter, nU_NSParameter, nB_PSG)
    End Function

    Public Overridable Function PRC_VRFN_WF_ETP_PREC(nU_NS As String, nU_ETP As Nullable(Of Short), dT_WF As ObjectParameter, bL_WF As ObjectParameter, [eRROR] As ObjectParameter) As Integer
        Dim nU_NSParameter As ObjectParameter = If(nU_NS IsNot Nothing, New ObjectParameter("NU_NS", nU_NS), New ObjectParameter("NU_NS", GetType(String)))

        Dim nU_ETPParameter As ObjectParameter = If(nU_ETP.HasValue, New ObjectParameter("NU_ETP", nU_ETP), New ObjectParameter("NU_ETP", GetType(Short)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("PRC_VRFN_WF_ETP_PREC", nU_NSParameter, nU_ETPParameter, dT_WF, bL_WF, [eRROR])
    End Function

End Class
