'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TMP_PST_CLSG
    Public Property LB_PST As String
    Public Property DT_SCAN As Date
    Public Property NM_OF As Nullable(Of Integer)
    Public Property CD_ARTI As String
    Public Property LB_ARTI As String
    Public Property NM_NS_EOL As String
    Public Property NM_MATR As Nullable(Of Short)

End Class
