'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class V_CFGR_CLIE
    Public Property NM_CLIE As String
    Public Property [OF] As String
    Public Property BL As String
    Public Property Numéro_de_carton As String
    Public Property Numéro_de_série_Eolane As String
    Public Property Numéro_de_série_client As String
    Public Property Carton_spécifique As String
    Public Property Code_fournisseur As String
    Public Property Suivi_numéro_de_série_par_ordre As String
    Public Property Format_du_code_fournisseur As String

End Class
