'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class V_CFGR_ARTI_ECO
    Public Property CD_ARTI As String
    Public Property Code_article_client As String
    Public Property Désignation_article_client As String
    Public Property [OF] As String
    Public Property BL As String
    Public Property Numéro_de_carton As String
    Public Property Numéro_de_série_Eolane As String
    Public Property Numéro_de_série_client As String
    Public Property Carton_spécifique As String
    Public Property Code_fournisseur As String
    Public Property Suivi_numéro_de_série_par_ordre As String
    Public Property Format_du_numéro_de_commande As String
    Public Property Format_du_numéro_de_BL As String
    Public Property Format_du_code_carton As String
    Public Property Format_du_code_fournisseur As String
    Public Property Format_Numéro_de_série_client As String
    Public Property Format_Numéro_de_série_Eolane As String
    Public Property Quantité_carton As String
    Public Property Quantité_flanc As String
    Public Property Incrémentation_flanc As String
    Public Property Retour_saisie_OF_pour_colisage As String
    Public Property Format_de_étiquette_Carton As String
    Public Property Encodage_Numéro_de_série_client As String
    Public Property Format_Numéro_de_série_Fournisseur As String
    Public Property Indice_client As String
    Public Property Nom_du_DDM As String
    Public Property Sous_ensemble_associé_n_1 As String
    Public Property Sous_ensemble_associé_n_2 As String
    Public Property Sous_ensemble_associé_n_3 As String
    Public Property Sous_ensemble_associé_n_4 As String
    Public Property Sous_ensemble_associé_n_5 As String
    Public Property Sous_ensemble_associé_n_6 As String
    Public Property Format_Numéro_de_lot As String
    Public Property Quantité_de_carton_dans_la_palette As String
    Public Property Nombre_de_ligne_dans_le_fichier_PDF As String
    Public Property Chemin_de_sauvegarde_du_fichier_PDF As String
    Public Property Impression_étiquette_packaging_numéro_de_série_Eolane As String
    Public Property Impression_étiquette_packaging_numéro_de_série_client As String
    Public Property Pourcentage_pour_la_recette_client As String
    Public Property Sérialisation_article As String
    Public Property Serveur_SMTP_mail As String
    Public Property Destinataires_mail As String
    Public Property Destinataires_en_copie_mail As String
    Public Property Destinataires_en_copie_cachée_mail As String
    Public Property Sujet_mail As String
    Public Property Contenu_mail As String
    Public Property Chemin_fichier_rapport_de_tracabilite As String
    Public Property Vue_fichier_PDF As String
    Public Property Vue_numéro_ensemble_numéros_sous_ensemble As String
    Public Property WORKFLOW_étape_1 As String
    Public Property WORKFLOW_étape_2 As String
    Public Property WORKFLOW_étape_3 As String
    Public Property WORKFLOW_étape_4 As String
    Public Property WORKFLOW_étape_5 As String
    Public Property WORKFLOW_étape_6 As String
    Public Property WORKFLOW_étape_7 As String
    Public Property WORKFLOW_étape_8 As String
    Public Property WORKFLOW_étape_9 As String
    Public Property WORKFLOW_étape_10 As String
    Public Property Génération_impression_numéro_de_série As String
    Public Property Format_numéro_de_série_Eolane_OF6INC As String
    Public Property Vérification_cohérence_OF_numero_serie_eolane As String
    Public Property Vérification_cohérence_OF_par_numéro_de_série As String
    Public Property Scan_numéro_de_série_fin_opération As String
    Public Property Format_UDI As String
    Public Property GTIN As String
    Public Property Document_carton_DF As String
    Public Property Document_palette_DF As String
    Public Property Document_BL_DF As String
    Public Property Requête_liste_produits_dans_le_carton_palette_document_DF As String
    Public Property Contenu_du_code_à_barre_document_DF As String
    Public Property Mise_à_disposition_des_documents_par_BL As String
    Public Property Nombre_étiquette_largeur As String

End Class
