'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class V_CLSG_PRD_DTM_HIST_LIVR
    Public Property ID_PSG As Long
    Public Property DT_SCAN As Date
    Public Property DT_EXPE As Nullable(Of Date)
    Public Property NU_CART As String
    Public Property NU_CMD As String
    Public Property NU_BL As String
    Public Property CD_CRTN As String
    Public Property NU_NS_EOL As String
    Public Property NU_NS_CLI As String
    Public Property NU_OF As Nullable(Of Integer)
    Public Property QT_CRTN As Nullable(Of Integer)
    Public Property NU_PALE As Nullable(Of Integer)
    Public Property NU_SER_ECO As String
    Public Property NU_SER_CLIE As String
    Public Property NU_UDI As String
    Public Property NU_ADRE_MAC As String
    Public Property NU_DEV_EUI As String

End Class
