'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class V_LIST_LIAI_NU_SER_ECO_NU_SER_CLIE
    Public Property NM_NS_EOL As String
    Public Property NM_NS_CLT As String
    Public Property NM_OF As Nullable(Of Integer)
    Public Property ID_PSG As Long

End Class
