'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class V_LIST_TEST_ODS_TEST_FONC_VAL
    Public Property Index_test As String
    Public Property Référence_banc_de_test As String
    Public Property Code_produit_en_test As String
    Public Property Nom_de_la_mesure As String
    Public Property Limite_inférieure As String
    Public Property Limite_supérieure As String
    Public Property Version_logicielle As String
    Public Property Version_séquentielle As String

End Class
