'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class V_NC_LIST_PHAS_FAIL_NU_SER_ID_SEQ
    Public Property NU_SER_SPFE As String
    Public Property ID_RFRC_SEQU As Long
    Public Property NU_PHAS_FCGF As Nullable(Of Short)
    Public Property NM_PHAS As String
    Public Property NU_SOUS_PHAS_FCGF As Nullable(Of Short)
    Public Property NM_SOUS_PHAS As String

End Class
