'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class V_NEW_RAPP_ODS_TEST_FONC_RAPP
    Public Property CD_PROD As String
    Public Property ID_MODE As String
    Public Property ID_EXEC As Long
    Public Property CD_OPER_TEST As String

End Class
