'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class V_NEOE_TRAC_ENS_SS_ENSE
    Public Property CD_PROD As String
    Public Property NM_NS_EOL As String
    Public Property DER_DATE_TEST As Nullable(Of Date)
    Public Property NU_PAD As String
    Public Property NU_PAIR As String

End Class
