'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class V_TCBL_TOUT
    Public Property NU_OF As Nullable(Of Integer)
    Public Property CD_DEVDEUI As String
    Public Property CD_MDP As String
    Public Property LB_STA As String
    Public Property ID_PSG As Integer
    Public Property DT_PSG As Nullable(Of Date)
    Public Property CD_ARTI As String
    Public Property BL_STA As Nullable(Of Boolean)
    Public Property NU_ETP As Nullable(Of Short)
    Public Property LB_ETP As String
    Public Property LB_CMRC As String
    Public Property LB_EOL As String
    Public Property CD_PN As String
    Public Property NU_VRSN As String
    Public Property NU_NS As String

End Class
