'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class DTM_REF_OPRT
    Public Property ID_OPRT As Short
    Public Property LB_INIT As String
    Public Property ID_HBLT_ALMS As Nullable(Of Byte)
    Public Property BL_ATVT As Nullable(Of Boolean)
    Public Property DT_ATVT As Nullable(Of Date)
    Public Property ID_MTCL_ECO As Nullable(Of Short)

End Class
