'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class DTM_NC_DETA
    Public Property NU_INCI As Integer
    Public Property DT_ITVT As Nullable(Of Date)
    Public Property ID_OPRT As Nullable(Of Short)
    Public Property BL_ETAT As Nullable(Of Boolean)
    Public Property ID_STAT As Byte
    Public Property ID_TYPE_CAUS As Nullable(Of Byte)

End Class
