'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class DTM_RESU_TEST_DETA
    Public Property NU_SER_SPFE As String
    Public Property NU_TEST As Byte
    Public Property NU_ORDR_SEQU As Short
    Public Property NU_TEST_PHAS As Short
    Public Property CD_ARTI_PROD As String
    Public Property ID_RFRC_SEQU As Long
    Public Property NU_PHAS_FCGF As Nullable(Of Short)
    Public Property NU_SOUS_PHAS_FCGF As Nullable(Of Short)
    Public Property BL_SORT_FCGF As Nullable(Of Boolean)
    Public Property NU_LIMI_BASS As Nullable(Of Double)
    Public Property NU_VALE As Nullable(Of Double)
    Public Property LB_VALE As String
    Public Property NU_LIMI_HAUT As Nullable(Of Double)
    Public Property ID_TEST As Nullable(Of Integer)
    Public Property NU_UNIT As String
    Public Property ID_STAT_PHAS As Nullable(Of Byte)
    Public Property BL_STAT_PHAS As Nullable(Of Boolean)
    Public Property ID_POST As String
    Public Property ID_OPRT As Nullable(Of Short)
    Public Property DT_TEST_PHAS As Nullable(Of Date)
    Public Property NB_TT As Nullable(Of Long)

End Class
