'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class DTM_PSG
    Public Property ID_PSG As Long
    Public Property LB_ETP As String
    Public Property DT_DEB As Date
    Public Property DT_FIN As Nullable(Of Date)
    Public Property LB_MOYN As String
    Public Property LB_PROG As String
    Public Property NM_MATR As Nullable(Of Integer)
    Public Property LB_DOC As String
    Public Property NM_NS_EOL As String
    Public Property LB_SCTN As String
    Public Property NM_OF As Nullable(Of Integer)
    Public Property ID_NU_SER As Nullable(Of Long)

End Class
