'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class DTM_REF_MTRE_LIST
    Public Property ID_MTRE As String
    Public Property BL_NATU As Nullable(Of Boolean)
    Public Property LB_DCPT As String
    Public Property BL_ATVT As Nullable(Of Boolean)
    Public Property DT_ATVT As Date
    Public Property BL_SORT_FCGF As Nullable(Of Boolean)

End Class
