'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class DTM_PSG_OUTI
    Public Property ID_PSG As Long
    Public Property NM_OUTI As String
    Public Property TP_OUTI As String
    Public Property DT_LIM_UTIL As Nullable(Of Date)

End Class
