'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class DTM_SEQU_RFRC_DETA
    Public Property ID_RFRC_SEQU As Long
    Public Property NU_PHAS_FCGF As Nullable(Of Short)
    Public Property NU_SOUS_PHAS_FCGF As Nullable(Of Short)
    Public Property NU_ORDR_SEQU As Short
    Public Property ID_TEST As Nullable(Of Integer)
    Public Property LB_MESS_ERRE As String
    Public Property NM_DRIV As String
    Public Property LB_PARA_DRIV As String
    Public Property ID_SAUT_PASS As Nullable(Of Short)
    Public Property ID_SAUT_FAIL As Nullable(Of Short)
    Public Property BL_EXCT As Nullable(Of Boolean)
    Public Property NU_LIMI_BASS As Nullable(Of Double)
    Public Property NU_LIMI_HAUT As Nullable(Of Double)
    Public Property BL_COMP_LIMI As Nullable(Of Boolean)
    Public Property BL_ERRE As Nullable(Of Boolean)
    Public Property BL_AFFI_FACE_AVAN_LABV As Nullable(Of Boolean)
    Public Property BL_RAPP_FCGF As Nullable(Of Boolean)
    Public Property BL_SORT_FCGF As Nullable(Of Boolean)
    Public Property NM_UNIT As String
    Public Property NM_PHAS_FCGF As String
    Public Property NM_SOUS_PHAS_FCGF As String
    Public Property BL_RAPP_ACTI As Nullable(Of Boolean)
    Public Property BL_CH_VAL As Nullable(Of Boolean)

End Class
