'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class DTM_REF_ENS
    Public Property ID_INTG As Integer
    Public Property CD_CLT_ENS As String
    Public Property CD_CLT_SENS As String
    Public Property QT_SENS As Nullable(Of Integer)
    Public Property LB_SENS As String
    Public Property CD_SAP_SENS As String
    Public Property CD_SAP_ENS As String
    Public Property LB_VRSN As String
    Public Property LB_PRDT As String
    Public Property CD_PRDT As String
    Public Property FT_NS_SENS As String
    Public Property FT_NS_ENS As String

End Class
