'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class DTM_ETP_WKF_OLD
    Public Property LB_ARTI As String
    Public Property NM_ORD As Integer
    Public Property LB_ETP As String
    Public Property NM_NBR As Nullable(Of Integer)

End Class
