'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class DTM_NU_SER
    Public Property NU_SER_SPFE As String
    Public Property CD_ARTI_PROD As String
    Public Property NU_OF As Nullable(Of Integer)
    Public Property ID_TYPE_NU_SER As Nullable(Of Byte)
    Public Property NU_SER As String

End Class
