'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class DTM_TST_RPRT
    Public Property ID_RPRT As Long
    Public Property LB_BNC As String
    Public Property CD_OPRT As String
    Public Property CD_PRDT As String
    Public Property NM_OF As String
    Public Property NM_NS As String
    Public Property DT_TST As Nullable(Of Date)
    Public Property LB_SNCT As String
    Public Property LB_MD As String
    Public Property VRS_LOG As String
    Public Property VRS_SEQ As String

End Class
