'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class V_CLSG_PRD_DTM_REF_ARTI_FT
    Public Property CD_ARTI_EOL As String
    Public Property FT_CMD As String
    Public Property FT_BL As String
    Public Property FT_CD_CRTN As String
    Public Property FT_FRNS As String
    Public Property BL_NS_CLI As Integer
    Public Property FT_NS_CLI As String
    Public Property BL_NS_EOL As Integer
    Public Property FT_NS_EOL As String
    Public Property QT_CRTN As String
    Public Property QT_FLAN As String
    Public Property INC_FLAN As String
    Public Property CD_ARTI_CLI As String

End Class
