'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class V_CLSG_PRD_DTM_REF_OPTN_CLI
    Public Property LB_CLI As String
    Public Property OPTN_OF As String
    Public Property OPTN_BL As String
    Public Property OPTN_N_CRTN As String
    Public Property OPTN_NS_EOL As String
    Public Property OPTN_NS_CLI As String
    Public Property OPTN_CRTN_SPEC As String
    Public Property OPTN_CD_FRNS As String
    Public Property FT_FRNS As String
    Public Property OPTN_SUIV_NU_SER_ORDR As String

End Class
