'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class V_CLSG_PRD_DTM_REF_PST
    Public Property LB_PST As String
    Public Property LB_IMP As String
    Public Property LB_FL_FRMT As String
    Public Property LB_IMP_BL As String
    Public Property LB_FL_FRMT_BL As String

End Class
