'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class V_DHR_ECAR_PDTO
    Public Property NM_DCPO_ANML As String
    Public Property NM_ACTI_REAL As String
    Public Property NU_SER_SPFE As String
    Public Property ID_OPRT_REAL As Nullable(Of Short)
    Public Property ID_OPRT_CONT As Nullable(Of Short)
    Public Property ID_STAT As String
    Public Property DT_ACTI_CONT As Nullable(Of Date)
    Public Property DT_ACTI_REAL As Nullable(Of Date)

End Class
