'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class V_DTM_TEST_FONC_RAPP
    Public Property ID_REF_BANC As String
    Public Property CD_OPER As String
    Public Property CD_PROD As String
    Public Property NU_OF As Nullable(Of Integer)
    Public Property NU_SER As String
    Public Property DT_TEST As Nullable(Of Date)
    Public Property DT_TEST_HEUR As Nullable(Of System.TimeSpan)
    Public Property BL_RES As String
    Public Property ID_MODE As String
    Public Property ID_VERS_LOG As String
    Public Property ID_VERS_SQC As String
    Public Property ID_EXEC As Long

End Class
