'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class V_DTM_TEST_FONC_VAL
    Public Property ID_REF_BANC As String
    Public Property CD_OPER As String
    Public Property CD_PROD As String
    Public Property NU_OF As Nullable(Of Integer)
    Public Property NU_SER As String
    Public Property DT_TEST As Date
    Public Property NM_MESU As String
    Public Property NU_LIM_INF As String
    Public Property NB_VAL As Nullable(Of Double)
    Public Property NU_LIM_SUP As String
    Public Property BL_SANC As String
    Public Property CH_VAL As String
    Public Property TU As Nullable(Of Integer)
    Public Property TT As Nullable(Of Integer)
    Public Property ID_VERS_LOG As String
    Public Property ID_VERS_SQC As String
    Public Property ID_EXEC As Nullable(Of Long)
    Public Property ID_TEST As Nullable(Of Long)

End Class
