'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class V_DTM_TEST_FONC_NOM_TEST
    Public Property ID_TEST As String
    Public Property ID_INDE As String
    Public Property ID_REF_BANC As String
    Public Property CD_PROD As String
    Public Property NM_MESU As String
    Public Property NU_LIM_INF As String
    Public Property NU_LIM_SUP As String
    Public Property ID_VERS_LOG As String
    Public Property ID_VERS_SQC As String
    Public Property NM_CHEM_PHOT_ETAP As String
    Public Property BL_ACVT_ETAP As String

End Class
