'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class V_FCGF_ANML
    Public Property NU_INCI As Integer
    Public Property NU_DRGT As String
    Public Property NU_SER_SPFE As String
    Public Property DT_ITVT As Nullable(Of Date)
    Public Property LB_INIT As String
    Public Property ID_MTCL_ECO As Nullable(Of Short)
    Public Property BL_ETAT As Nullable(Of Boolean)
    Public Property LB_DCPT_STAT As String
    Public Property NM_DCPO_NC As String
    Public Property NM_TYPE_NC As String
    Public Property NM_RFRC_SEQU As String
    Public Property NU_VERS_SEQU As Byte
    Public Property NM_PHAS As String
    Public Property NM_SOUS_PHAS As String
    Public Property CD_ARTI_DFTE As String
    Public Property NM_DSGT_DEFA As String
    Public Property NM_RSLT As String
    Public Property NM_RFRC_SEQU_RETO As String
    Public Property NU_VERS_SEQU_RETO As Byte
    Public Property NM_PHAS_RETO As String

End Class
