'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class V_FCGF
    Public Property NU_SER_SPFE As String
    Public Property NM_RFRC_SEQU As String
    Public Property NU_VERS_SEQU As Nullable(Of Byte)
    Public Property NM_RFRC_FDV As String
    Public Property NU_VERS_FDV As Nullable(Of Byte)
    Public Property LB_STAT_PROD As String
    Public Property NM_STAT_PROD As String
    Public Property NU_OF As Nullable(Of Integer)
    Public Property DT_TEST As Nullable(Of Date)
    Public Property NM_PHAS As String
    Public Property NM_SOUS_PHAS As String
    Public Property NU_LIMI_BASS As String
    Public Property NU_VALE As String
    Public Property LB_VALE As String
    Public Property NU_LIMI_HAUT As String
    Public Property NU_UNIT As String
    Public Property LB_DCPT_STAT As String
    Public Property LB_STAT_PHAS As String
    Public Property ID_POST As String
    Public Property ID_OPRT As Nullable(Of Short)
    Public Property NU_OP As Nullable(Of Integer)
    Public Property NU_ORDR_SEQU As Short
    Public Property NU_PHAS_FCGF As Nullable(Of Short)
    Public Property NU_SOUS_PHAS_FCGF As Nullable(Of Short)
    Public Property BL_STAT_PHAS As Nullable(Of Boolean)

End Class
