'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class V_NC_LIST_CD_ARTI_TCBL_UNIT
    Public Property CD_ARTI_COMP As String
    Public Property CD_ARTI_PROD As String
    Public Property BL_TYPE_TCBL As Nullable(Of Boolean)
    Public Property ID_TYPE_CAUS As Nullable(Of Byte)

End Class
