'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class V_NC_LIST_PROD_RETO_PDTO
    Public Property ID_RFRC_SEQU_RETO As Nullable(Of Long)
    Public Property NU_PHAS_FCGF_RETO As Nullable(Of Short)
    Public Property NU_SER_SPFE As String
    Public Property MAX_ID_STAT As Nullable(Of Byte)
    Public Property NU_INCI As Integer

End Class
