'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class V_NC_LIST_SEQU_FAIL_NU_SER
    Public Property NU_SER_SPFE As String
    Public Property NM_RFRC_SEQU As String
    Public Property MAX_NU_TEST As Nullable(Of Byte)
    Public Property ID_RFRC_SEQU As Long
    Public Property DT_TEST As Date

End Class
