'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class V_NEW_TEST_ODS_TEST_FONC_VAL
    Public Property NM_CRIT As Nullable(Of Long)
    Public Property NM_PARA As String
    Public Property VAL_PARA As String
    Public Property DT_PARA As Date

End Class
