'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class V_NEW_VALE_ODS_TEST_FONC_VAL
    Public Property ID_EXEC As Long
    Public Property ID_TEST As String
    Public Property NB_VAL As String
    Public Property CH_VAL As String
    Public Property TU As String
    Public Property TT As String

End Class
