'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class V_NEOE_NU_SER_ECO_NU_SER_SS_ENS
    Public Property CD_PROD As String
    Public Property NU_SER_SOUS_ENSE As String
    Public Property NU_SER_ECO As String

End Class
