'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class V_POST_FCGF
    Public Property ID_POST As String
    Public Property ID_MTRE As String
    Public Property DT_AFCT As Nullable(Of Date)
    Public Property DT_VLDT As Date
    Public Property NM_TYPE_MTRE As String

End Class
