'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class V_RSLT_POIN_ARRE_TCBL_OPRT
    Public Property NU_SER_ECO As String
    Public Property NU_SER_CLIE As String
    Public Property NU_OF As String
    Public Property LB_SCTN As String
    Public Property NM_MATR As Nullable(Of Integer)
    Public Property LB_PROG As String
    Public Property LB_MOYN As String
    Public Property DT_DEB As Date
    Public Property DT_FIN As Nullable(Of Date)
    Public Property LB_ETP As String
    Public Property NB_VAL As Nullable(Of Double)
    Public Property CH_VAL As String
    Public Property TU As Nullable(Of Integer)
    Public Property TT As Nullable(Of Integer)
    Public Property ID_TEST As Nullable(Of Long)
    Public Property CD_ARTI As String
    Public Property ID_INDE As String
    Public Property LB_CONS_ETAP As String
    Public Property NM_CHEM_PHOT_ETAP As String
    Public Property NU_LIMI_IFRE_ETAP As String
    Public Property NU_LIMI_SPRE_ETAP As String
    Public Property NU_VERS_ETAP As String

End Class
