'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class V_SERE_ARTI
    Public Property Code_article As String
    Public Property Nom_article As String
    Public Property Code_article_EC As String
    Public Property C__RECETTE As String
    Public Property sérialisé As String

End Class
