'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class V_TAE_TCBL_HSRQ_STAT_PROD
    Public Property NM_NS_CLT As String
    Public Property RN As Nullable(Of Long)
    Public Property ID_RFRC_SEQU As Short
    Public Property LB_SCTN As Integer
    Public Property DT_DEB As Date
    Public Property NM_MATR As Nullable(Of Integer)
    Public Property LB_MOYN As String

End Class
