'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class V_TAE_TCBL_NMCT_UNIT_PROD
    Public Property NU_SER_PROD As String
    Public Property CD_ARTI_PROD As String
    Public Property NU_SER_COMP As String
    Public Property CD_ARTI_COMP As String
    Public Property NM_DSGT_COMP As String
    Public Property NM_TYPE_TCBL As Integer
    Public Property DT_AFTT As Nullable(Of Date)

End Class
